/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Raffle {
  export type LotPlayerStruct = { name: string; color: string };

  export type LotPlayerStructOutput = [name: string, color: string] & {
    name: string;
    color: string;
  };

  export type LotRoomStruct = {
    players: Raffle.LotPlayerStruct[];
    creationDate: BigNumberish;
    exists: boolean;
    winner: string;
    requestId: BigNumberish;
  };

  export type LotRoomStructOutput = [
    players: Raffle.LotPlayerStructOutput[],
    creationDate: bigint,
    exists: boolean,
    winner: string,
    requestId: bigint,
  ] & {
    players: Raffle.LotPlayerStructOutput[];
    creationDate: bigint;
    exists: boolean;
    winner: string;
    requestId: bigint;
  };
}

export interface RaffleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_PLAYERS"
      | "RequestIdsRoom"
      | "acceptOwnership"
      | "createNewLotRoom"
      | "deleteMyRoom"
      | "getMyRoomInfo"
      | "getRoomInfo"
      | "lotRooms"
      | "owner"
      | "rawFulfillRandomWords"
      | "s_vrfCoordinator"
      | "selectWinner"
      | "setCoordinator"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CoordinatorSet"
      | "OwnershipTransferRequested"
      | "OwnershipTransferred"
      | "RoomSelectWinnerFulfilled"
      | "RoomSelectWinnerStarted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MIN_PLAYERS", values?: undefined): string;
  encodeFunctionData(functionFragment: "RequestIdsRoom", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "acceptOwnership", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createNewLotRoom",
    values: [Raffle.LotPlayerStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "deleteMyRoom", values?: undefined): string;
  encodeFunctionData(functionFragment: "getMyRoomInfo", values?: undefined): string;
  encodeFunctionData(functionFragment: "getRoomInfo", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "lotRooms", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "s_vrfCoordinator", values?: undefined): string;
  encodeFunctionData(functionFragment: "selectWinner", values?: undefined): string;
  encodeFunctionData(functionFragment: "setCoordinator", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "transferOwnership", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "MIN_PLAYERS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RequestIdsRoom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "acceptOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createNewLotRoom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deleteMyRoom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMyRoomInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRoomInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lotRooms", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rawFulfillRandomWords", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "s_vrfCoordinator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "selectWinner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCoordinator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transferOwnership", data: BytesLike): Result;
}

export namespace CoordinatorSetEvent {
  export type InputTuple = [vrfCoordinator: AddressLike];
  export type OutputTuple = [vrfCoordinator: string];
  export interface OutputObject {
    vrfCoordinator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferRequestedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomSelectWinnerFulfilledEvent {
  export type InputTuple = [roomOwner: AddressLike, winner: string];
  export type OutputTuple = [roomOwner: string, winner: string];
  export interface OutputObject {
    roomOwner: string;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomSelectWinnerStartedEvent {
  export type InputTuple = [roomOwner: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [roomOwner: string, requestId: bigint];
  export interface OutputObject {
    roomOwner: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Raffle extends BaseContract {
  connect(runner?: ContractRunner | null): Raffle;
  waitForDeployment(): Promise<this>;

  interface: RaffleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  MIN_PLAYERS: TypedContractMethod<[], [bigint], "view">;

  RequestIdsRoom: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  createNewLotRoom: TypedContractMethod<[players: Raffle.LotPlayerStruct[]], [void], "nonpayable">;

  deleteMyRoom: TypedContractMethod<[], [void], "nonpayable">;

  getMyRoomInfo: TypedContractMethod<[], [Raffle.LotRoomStructOutput], "view">;

  getRoomInfo: TypedContractMethod<[roomOwner: AddressLike], [Raffle.LotRoomStructOutput], "view">;

  lotRooms: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, boolean, string, bigint] & {
        creationDate: bigint;
        exists: boolean;
        winner: string;
        requestId: bigint;
      },
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  rawFulfillRandomWords: TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  s_vrfCoordinator: TypedContractMethod<[], [string], "view">;

  selectWinner: TypedContractMethod<[], [bigint], "nonpayable">;

  setCoordinator: TypedContractMethod<[_vrfCoordinator: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "MIN_PLAYERS"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RequestIdsRoom"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(nameOrSignature: "acceptOwnership"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createNewLotRoom"
  ): TypedContractMethod<[players: Raffle.LotPlayerStruct[]], [void], "nonpayable">;
  getFunction(nameOrSignature: "deleteMyRoom"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMyRoomInfo"
  ): TypedContractMethod<[], [Raffle.LotRoomStructOutput], "view">;
  getFunction(
    nameOrSignature: "getRoomInfo"
  ): TypedContractMethod<[roomOwner: AddressLike], [Raffle.LotRoomStructOutput], "view">;
  getFunction(nameOrSignature: "lotRooms"): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, boolean, string, bigint] & {
        creationDate: bigint;
        exists: boolean;
        winner: string;
        requestId: bigint;
      },
    ],
    "view"
  >;
  getFunction(nameOrSignature: "owner"): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rawFulfillRandomWords"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(nameOrSignature: "s_vrfCoordinator"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "selectWinner"): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "setCoordinator"
  ): TypedContractMethod<[_vrfCoordinator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CoordinatorSet"
  ): TypedContractEvent<
    CoordinatorSetEvent.InputTuple,
    CoordinatorSetEvent.OutputTuple,
    CoordinatorSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested"
  ): TypedContractEvent<
    OwnershipTransferRequestedEvent.InputTuple,
    OwnershipTransferRequestedEvent.OutputTuple,
    OwnershipTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RoomSelectWinnerFulfilled"
  ): TypedContractEvent<
    RoomSelectWinnerFulfilledEvent.InputTuple,
    RoomSelectWinnerFulfilledEvent.OutputTuple,
    RoomSelectWinnerFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "RoomSelectWinnerStarted"
  ): TypedContractEvent<
    RoomSelectWinnerStartedEvent.InputTuple,
    RoomSelectWinnerStartedEvent.OutputTuple,
    RoomSelectWinnerStartedEvent.OutputObject
  >;

  filters: {
    "CoordinatorSet(address)": TypedContractEvent<
      CoordinatorSetEvent.InputTuple,
      CoordinatorSetEvent.OutputTuple,
      CoordinatorSetEvent.OutputObject
    >;
    CoordinatorSet: TypedContractEvent<
      CoordinatorSetEvent.InputTuple,
      CoordinatorSetEvent.OutputTuple,
      CoordinatorSetEvent.OutputObject
    >;

    "OwnershipTransferRequested(address,address)": TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;
    OwnershipTransferRequested: TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RoomSelectWinnerFulfilled(address,string)": TypedContractEvent<
      RoomSelectWinnerFulfilledEvent.InputTuple,
      RoomSelectWinnerFulfilledEvent.OutputTuple,
      RoomSelectWinnerFulfilledEvent.OutputObject
    >;
    RoomSelectWinnerFulfilled: TypedContractEvent<
      RoomSelectWinnerFulfilledEvent.InputTuple,
      RoomSelectWinnerFulfilledEvent.OutputTuple,
      RoomSelectWinnerFulfilledEvent.OutputObject
    >;

    "RoomSelectWinnerStarted(address,uint256)": TypedContractEvent<
      RoomSelectWinnerStartedEvent.InputTuple,
      RoomSelectWinnerStartedEvent.OutputTuple,
      RoomSelectWinnerStartedEvent.OutputObject
    >;
    RoomSelectWinnerStarted: TypedContractEvent<
      RoomSelectWinnerStartedEvent.InputTuple,
      RoomSelectWinnerStartedEvent.OutputTuple,
      RoomSelectWinnerStartedEvent.OutputObject
    >;
  };
}
